### ISSUE TITLE
Install on Ubuntu on bower install task

### ISSUE THREAD

**Issue by tonyarnold99** [PaloAltoNetworks/minemeld-ansible#39]
Installing on Ubuntu 16.04 fails on the 'bower install' task in webui.yml. Error returned is 'Request to https://bower.herokuapp.com/packages/angular-ui-router failed with 502'.

Visiting this site in a web browser returns 'This Bower version is deprecated. Please update it: npm install -g bower. The new registry address is https://registry.bower.io', so I presume the playbook is installing an out of date version of bower.

Here is the full output when using -vv on the ansible-playbook command:

TASK [minemeld : bower install] ************************************************************************************************
task path: /home/vagrant/minemeld-ansible/roles/minemeld/tasks/webui.yml:22
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": ["bower", "install", "--allow-root"], "delta": "0:00:00.909559", "end": "2018-06-25 04:05:05.873583", "msg": "non-zero return code", "rc": 1, "start": "2018-06-25 04:05:04.964024", "stderr": "bower                     invalid-meta The \"name\" is recommended to be lowercase, can contain digits, dots, dashes\nbower angular-ui-router#~0.2.15          EINVRES Request to https://bower.herokuapp.com/packages/angular-ui-router failed with 502", "stderr_lines": ["bower                     invalid-meta The \"name\" is recommended to be lowercase, can contain digits, dots, dashes", "bower angular-ui-router#~0.2.15          EINVRES Request to https://bower.herokuapp.com/packages/angular-ui-router failed with 502"], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/home/vagrant/minemeld-ansible/local.retry

**Comment by jtschichold** [comment]
Hi @tonyarnold99,
thanks, I have merged a PR in minemeld-webui (PaloAltoNetworks/minemeld-webui#118) that should solve this. Could you try again?

**Comment by tonyarnold99** [comment]
Hi Luigi,

I have tried installing again and all worked successfully. Many thanks.

Regards,
Tony.

**Comment by jtschichold** [comment]
Awesome! thanks!
