### ISSUE TITLE
Ansible playbook fails on RHEL 7.5

### ISSUE THREAD

**Issue by inurbits** [PaloAltoNetworks/minemeld-ansible#48]
After checking out a new copy of the ansible playbook I get the following error on RHEL 7.5:

`TASK [minemeld : minemeld-core repo] ******************************************************************************
fatal: [127.0.0.1]: FAILED! => {"before": "1d537501cdb80139174e2c858f9b2f6ae779bb19", "changed": false, "msg": "Local modifications exist in repository (force=no)."}
        to retry, use: --limit @/home/secadmin/minemeld-ansible/local.retry

PLAY RECAP ********************************************************************************************************
127.0.0.1                  : ok=33   changed=2    unreachable=0    failed=1
`

I'm following the install guide and running the command:
ansible-playbook -K -i 127.0.0.1, local.yml

No changes made to the local.yml file. Any ideas for troubleshooting this?

**Comment by inurbits** [comment]
I managed to figure this out. I needed to edit roles/minemeld/tasks/core.yml and add "force: yes" to the git section.

**Comment by iamarunix** [comment]
Even I made force=yes in the playbook, then it got worked.

thanks
