### ISSUE TITLE
How do minemeld Ansible users update their minemeld version to the latest release?

### ISSUE THREAD

**Issue by da667** [PaloAltoNetworks/minemeld-ansible#49]
Currently running minemeld version .9.44 and apparently .9.50 has been around for a while. All the documentation you have available refers to a script called 'minemeld-auto-update' that doesn't exist at all on my system.

OS: Ubuntu 16.04
Minemeld Version: .9.44
Problem: /usr/sbin/minemeld-auto-update doesn't exist. How do minemeld-ansible users update their minemeld instances?

**Comment by jtschichold** [comment]
Good question.

You can use the following to update MM to the latest release (note that all the configs and data are stored under /opt/minemeld/local and **won't** be lost during the procedure):
```
$ sudo systemctl stop minemeld.service
$ sudo rm -rf /opt/minemeld/engine/ /opt/minemeld/prototypes/ /opt/minemeld/www/
$ cd minemeld-ansible
$ ansible-playbook -K -i 127.0.0.1, local.yml
$ shutdown -r now
```
*If you are using extensions, the engine won't start. Reactivate the extensions from the WebUI after the upgrade and restart the engine*

**Comment by kevinsteves** [comment]
upgrade steps have been incorporated in the README.md (currently in develop branch).
